### ISSUE TITLE
"Check for ip address in config file" failing

### ISSUE THREAD

**Issue by kfitzpatrick** [palkan-ansible/influxdb#1]
When using this role, I got an error when checking for the ip address in the config file. Turns out the config toml file isn't there yet. 

> TASK: [palkan.influxdb | InfluxDB | Check for ip address in config file] *****\* 
> failed: [localhost] => {"changed": false, "cmd": ["grep", "-E", "^\s_hostname._104.131.15.20", "/opt/influxdb/shared/config.toml"], "delta": "0:00:00.003042", "end": "2015-07-01 19:38:22.317988", "rc": 2, "start": "2015-07-01 19:38:22.314946", "stdout_lines": [], "warnings": []}
> stderr: grep: /opt/influxdb/shared/config.toml: No such file or directory
> ...ignoring

**Comment by kfitzpatrick** [comment]
There is, however, a config file in `/etc/opt/influxdb/influxdb.conf`

**Comment by palkan** [comment]
Yeah, the path was incorrect. Fixed.
Thanks!

**Comment by kfitzpatrick** [comment]
Thanks for the quick response!
